### ISSUE TITLE
its not using GPU only CPU?

### ISSUE THREAD

**Issue by CKay010** [jamiepine/voicebox#141]
Just tried the voicebox, its just only using CPU not the gpu how do i enable it?

**Comment by ajayduraisamy** [comment]
> Just tried the voicebox, its just only using CPU not the gpu how do i enable it?

This is currently a known issue affecting many Windows users (similar to #84 and #127). The app currently fails to properly link the CUDA environment on Windows v0.1.12.

Temporary Fixes to try:

Check CUDA Path: Ensure you have CUDA Toolkit 12.1+ installed and your PATH environment variables are set.

Manual Torch Install: If you are running from source, go to the /backend folder and run:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Verify Settings: Check the 'Provider Settings' in the app; if it says 'GPU: Not Available,' it will default to CPU.

Note for Laptop Users: Generating on CPU can cause significant thermal stress and may trigger hardware errors (like HP 90B Fan Error) due to the high intensity of the Qwen3-TTS model."

**Comment by CHKE9** [comment]
> > Just tried the voicebox, its just only using CPU not the gpu how do i enable it?
> 
> This is currently a known issue affecting many Windows users (similar to [#84](https://github.com/jamiepine/voicebox/issues/84) and [#127](https://github.com/jamiepine/voicebox/issues/127)). The app currently fails to properly link the CUDA environment on Windows v0.1.12.
> 
> Temporary Fixes to try:
> 
> Check CUDA Path: Ensure you have CUDA Toolkit 12.1+ installed and your PATH environment variables are set.
> 
> Manual Torch Install: If you are running from source, go to the /backend folder and run: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
> 
> Verify Settings: Check the 'Provider Settings' in the app; if it says 'GPU: Not Available,' it will default to CPU.
> 
> Note for Laptop Users: Generating on CPU can cause significant thermal stress and may trigger hardware errors (like HP 90B Fan Error) due to the high intensity of the Qwen3-TTS model."

i used the exe version, did run the cmd on /backend here C:\Users\user\AppData\Local\Voicebox it didnt fix it, did i do it wrong?  im on 5090

**Comment by Nomi1212453** [comment]
How long will it take to fix this problem??? I'm on Windows 11, the shittest one of them all after window vista and using a crappy 50 series card I still miss my 3090 that thing never caused me so much headache

**Comment by ajayduraisamy** [comment]
The reason the previous fix didn't work for you is that the RTX 5090 uses the new Blackwell architecture (sm_120), which isn't supported by the standard CUDA 12.1 torch wheels. You need to force-install the CUDA 12.8 Nightly build into the Voicebox backend.

Since you are using the EXE version, try this exact command inside your C:\Users\user\AppData\Local\Voicebox\backend folder:

Open CMD as Administrator.

Navigate to the backend: cd C:\Users\user\AppData\Local\Voicebox\backend

Run this command to overwrite the incompatible version:
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall

Note: If the app uses a built-in python.exe inside that folder, use .\python.exe -m pip install... instead to ensure it hits the right spot.

**Comment by CHKE9** [comment]
> How long will it take to fix this problem??? I'm on Windows 11, the shittest one of them all after window vista and using a crappy 50 series card I still miss my 3090 that thing never caused me so much headache

bro chill this fixed it 
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall

**Comment by CountCandy** [comment]
I hate to ask, but where exactly did you open your terminal in the 'backend'? I tried randomly for a bit with no luck and was hoping someone could help me with an admittedly dumb question. 

Here is what I find when I look at my local folder (C:\Users\yadayada\AppData\Local\sh.voicebox.app\EBWebView)

<img width="479" height="489" alt="Image" src="https://github.com/user-attachments/assets/5746ab33-2cec-4e84-a89d-beddffede8cc" />

**Comment by duyduc27** [comment]
> bro chill this fixed it pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall

It doesn't work for me.  I ran it in C:\Users\MyUserName\AppData\Local\sh.voicebox.app\EBWebView

And it still shows "CPU only"

**Comment by NorthOfEarth** [comment]
Edit: Solved!

1) Download and install CUDA toolkit: https://developer.nvidia.com/cuda/toolkit
2) Build from source (ask ChatGPT or something if you need detailed instructions)
3) BEFORE launching the app with _bun run dev_, run:
_pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall_

Works fine now. Windows 10 + 4080.

If you did any of this out of order, just uninstall everything, reboot, and start from scratch.

**Comment by helpmebro911** [comment]
pls fix bug
It is also worth making a portable version of the program for ease of use

**Comment by CHKE9** [comment]
> pls fix bug It is also worth making a portable version of the program for ease of use

Yes that would be easy! :)

**Comment by CHKE9** [comment]
BTW its very slow on 5090 even it detect graphic card

**Comment by LucianoDaluz** [comment]
Same here

**Comment by sameul674** [comment]
>will be fixed in the next update
>update arrives
>still not fixed

**Comment by sumire608** [comment]
https://github.com/sumire608/voicebox/releases/tag/v0.1.13
I build with CUDA ver 0.1.13, you can try it.

**Comment by Archviz360** [comment]
<img width="809" height="218" alt="Image" src="https://github.com/user-attachments/assets/019b9a99-8b14-4733-ba9f-ba68d62c046f" />
<img width="1105" height="723" alt="Image" src="https://github.com/user-attachments/assets/a03c68f1-4790-4cbd-ae1a-730de4df64a6" />

Still not working.

**Comment by sumire608** [comment]
> <img alt="Image" width="809" height="218" src="https://private-user-images.githubusercontent.com/82177593/554893135-019b9a99-8b14-4733-ba9f-ba68d62c046f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzIwNjM1MjIsIm5iZiI6MTc3MjA2MzIyMiwicGF0aCI6Ii84MjE3NzU5My81NTQ4OTMxMzUtMDE5YjlhOTktOGIxNC00NzMzLWJhOWYtYmE2OGQ2MmMwNDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI1VDIzNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjUzNzQwN2M3NDM2NGY1MDY0ZDZlZTZlMjdiNTE3Y2MzYzM4OWU1OWRjOTMyM2NjOWU5OGFmZGFhN2NjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bDNJo8vrv16JKcHYV6644TegI-9CYaEfXw_DYdYzqHs"> <img alt="Image" width="1105" height="723" src="https://private-user-images.githubusercontent.com/82177593/554893138-a03c68f1-4790-4cbd-ae1a-730de4df64a6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzIwNjM1MjIsIm5iZiI6MTc3MjA2MzIyMiwicGF0aCI6Ii84MjE3NzU5My81NTQ4OTMxMzgtYTAzYzY4ZjEtNDc5MC00Y2JkLWFlMWEtNzMwZGU0ZGY2NGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjI1VDIzNDcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYTM5ODI5ZDU5OWRiZjc0ZWQwNWFlYzUzYzgzYjJhNTRkODVmM2FmNDdlMjQzNDdlNmMyYmUxMDMzYTIyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KsbPMyF8ImOGSx2we0JjxceV-qw0Irxl1cIiDHX7DIE">
> Still not working.

need CUDA 13.0 or above

**Comment by robrowald** [comment]
I have Cuda 13.1 and it doesn't work
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.59                 Driver Version: 591.59         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+

**Comment by sumire608** [comment]
You may need to use taskmgr and killed "voicebox-server.exe" processes manually, because they won't exit automatically. Then try again.

**Comment by robrowald** [comment]
> You may need to use taskmgr and killed "voicebox-server.exe" processes manually, because they won't exit automatically. Then try again.

Tried that too. same result.

**Comment by sumire608** [comment]
Ok, no idea then...

**Comment by sumire608** [comment]
I may got the release files wrong. So I build it again today. Make sure the file is 1.88GB.
https://github.com/sumire608/voicebox/releases

**Comment by robrowald** [comment]
> I may got the release files wrong. So I build it again today. Make sure the file is 1.88GB. https://github.com/sumire608/voicebox/releases

downloading now will report back

**Comment by robrowald** [comment]
<img width="1093" height="331" alt="Image" src="https://github.com/user-attachments/assets/cd11ba1c-9725-448a-8adf-7657ae38890b" />

seems to work now

**Comment by robrowald** [comment]
<img width="627" height="505" alt="Image" src="https://github.com/user-attachments/assets/979ba418-274c-4e3a-8254-25adccb43ac2" /> Can confirmm it uses the GPU. Thanks!

**Comment by duyduc27** [comment]
> I may got the release files wrong. So I build it again today. Make sure the file is 1.88GB. https://github.com/sumire608/voicebox/releases

It works to me. Thank you a lot man! 

Note: Even with GPU, it is still so slow to render an audio....

**Comment by sumire608** [comment]
> > I may got the release files wrong. So I build it again today. Make sure the file is 1.88GB. https://github.com/sumire608/voicebox/releases
> 
> It works to me. Thank you a lot man!
> 
> Note: Even with GPU, it is still so slow to render an audio....

Currently this model can just for fun. Wait for next generation.

**Comment by jamiepine** [comment]
This should be resolved in **Voicebox v0.2.x**! 🎉

GPU detection and CUDA support have been completely reworked:

- **CUDA backend swap** — the app now ships with a CPU backend by default, and you can download and install the CUDA-accelerated backend directly from **Settings → GPU Acceleration**. No reinstall or manual setup required.
- **AMD ROCm** support on Linux
- **Intel Arc (XPU)** and **DirectML** support on Windows

If you're on Windows with an NVIDIA GPU: update to v0.2.x, go to Settings → GPU Acceleration, and download the CUDA backend. It'll swap in automatically and your GPU should be detected on the next generation.

**To get the update:**
- Download the latest release from [voicebox.sh](https://voicebox.sh) or update from within the app

Closing as resolved — if you still have GPU detection issues on v0.2.x after installing the CUDA backend, please open a new issue with your GPU model and OS details!

**Comment by RikusLategan** [comment]
> I hate to ask, but where exactly did you open your terminal in the 'backend'? I tried randomly for a bit with no luck and was hoping someone could help me with an admittedly dumb question.
> 
> Here is what I find when I look at my local folder (C:\Users\yadayada\AppData\Local\sh.voicebox.app\EBWebView)
> 
> <img alt="Image" width="479" height="489" src="https://private-user-images.githubusercontent.com/134805831/553072756-5746ab33-2cec-4e84-a89d-beddffede8cc.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwNjU3MzcsIm5iZiI6MTc3NzA2NTQzNywicGF0aCI6Ii8xMzQ4MDU4MzEvNTUzMDcyNzU2LTU3NDZhYjMzLTJjZWMtNGU4NC1hODlkLWJlZGRmZmVkZThjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQyNFQyMTE3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTI0MWI5YTllNzk0MmRhOTkwMTIyOThiMzdiZmYyZTk0MGZiZTczYWIxYzU0MDA5MmI2OTQxZGFmNzU4MzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.b_20fFiQxnyqbSmTy9tZd0NU1q9qk3S9jIct3FXXOCQ">

That looks like an electron database.  You need to look in Appdata\Remote not Appdata\Local
