### ISSUE TITLE
[Bug] CUDA Error: no kernel image is available for NVIDIA RTX 50-series (Blackwell / sm_120)

### ISSUE THREAD

**Issue by rokonmd111** [jamiepine/voicebox#362]
### Describe the bug
I am experiencing a `CUDA error: no kernel image is available for execution` when trying to generate audio or download new models (like Chatterbox) on my new **NVIDIA GeForce RTX 5070 Ti**.

The issue is that the current bundled PyTorch/CUDA version in Voicebox (v0.3.x) does not support the **Blackwell architecture (Compute Capability 12.0 / sm_120)**. 

### To Reproduce
1. Install Voicebox on a Windows machine with an RTX 50-series GPU.
2. Attempt to generate audio using any engine (Qwen3-TTS or Chatterbox).
3. See the error: `torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device`.

### Error Logs

<img width="375" height="308" alt="Image" src="https://github.com/user-attachments/assets/70857d61-8482-411a-a0b6-3abedd53d0dc" />
<img width="1220" height="864" alt="Image" src="https://github.com/user-attachments/assets/7dc1c814-0c96-4d14-8601-60b67655a40e" />

```text
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
Search for `cudaErrorNoKernelImageForDevice' in [https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html)
UserWarning: NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
```

Environment
OS: Windows 10/11

GPU: NVIDIA GeForce RTX 5070 Ti (Blackwell)

Voicebox Version: v0.3.1

Python Version: 3.10 / 3.11

PyTorch Version (bundled): 2.x (Currently lacks sm_120 support)

Expected behavior
The application should use a PyTorch Nightly build or a version that supports CUDA 12.4+ and Blackwell architecture to enable compatibility with RTX 50-series GPUs.

Additional context
I manually tested with torch-nightly (cu128) in a separate venv and it detected the GPU correctly, but the compiled Windows app (Tauri) hangs on splash screen when trying to connect to a manual backend. We need an official update with updated PyTorch binaries.

**Comment by mattoftheland** [comment]
Dev said it's getting fixed in the next release (0.4.0).  https://github.com/jamiepine/voicebox/issues/301

**Comment by xxx-xxx-xxx-xxx-xxx-xxx** [comment]
I can confirm I got the same error message on RTX 5060 Ti 16GB.

<img width="408" height="347" alt="Image" src="https://github.com/user-attachments/assets/62bba81d-0a67-41d2-a5e9-48fbb6df61a6" />

**Comment by duquevazzaro** [comment]
I've compiled a version that includes CUDA support for the RTX 50 Series. I have an RTX 5080, and it works perfectly. If anyone's interested, I'll upload the release to my GitHub so you can try it out and give me some feedback.

**Comment by Musaab9090** [comment]
> I've compiled a version that includes CUDA support for the RTX 50 Series. I have an RTX 5080, and it works perfectly. If anyone's interested, I'll upload the release to my GitHub so you can try it out and give me some feedback.

im interested , been trying to solve this issue for the past couple of days but to no avail
