### ISSUE TITLE
CUDA Error: cudaErrorNoKernelImageForDevice during generation

### ISSUE THREAD

**Issue by ApexLiberta** [jamiepine/voicebox#395]
I am encountering a runtime error when attempting to run the generation script for Voicebox. The process fails immediately with a CUDA kernel image error, suggesting a mismatch between the compiled binaries and my GPU hardware.

> ### Error

> Generation failed
> 
> CUDA error: no kernel image is available for
> execution on the device Search for
> `cudaErrorNoKernellmageForDevice' in
> https://docs.nvidia.com/cuda/cuda-runtime-
> api/group_CUDART_TYPES.html for more
> information. CUDA kernel errors might be
> asynchronously reported at some other API call, so
> the stacktrace below might be incorrect. For
> debugging consider passing
> CUDA_LAUNCH_BLOCKING=1 Compile with
> `TORCH_USE_CUDA_DSA` to enable device-side
> assertions.

- Gpu: 5060ti 16gb
- Driver: 595.97
- OS: Win 11

**Comment by thackeba** [comment]
I have been having the same issue with my 5090 as well.

**Comment by duquevazzaro** [comment]
I've compiled a version that includes CUDA support for the RTX 50 Series. I have an RTX 5080, and it works perfectly. If anyone's interested, I'll upload the release to my GitHub so you can try it out and give me some feedback.

**Comment by platinumturtle** [comment]
I'm having the same problem but using a RTX 5070 Ti, @duquevazzaro maybe your version could be our solution to this issue

**Comment by duquevazzaro** [comment]
> I'm having the same problem but using a RTX 5070 Ti, [@duquevazzaro](https://github.com/duquevazzaro) maybe your version could be our solution to this issue

I'll get right on it. I'll let you know when the source code and the release are uploaded to my Git :)

**Comment by Jhonatanjhs** [comment]
Nice! That'd be great

**Comment by duquevazzaro** [comment]
> Nice! That'd be great

Ready guys https://github.com/duquevazzaro/clonvoice-releases/tree/main
Buy me a coffee :)
