### ISSUE TITLE
CUDA error on RTX 5080 (sm_120/Blackwell) — PyTorch not compiled for sm_120

### ISSUE THREAD

**Issue by fanhua2022-commits** [jamiepine/voicebox#396]
VoiceBox v0.3.0, Windows 11, NVIDIA GeForce RTX 5080
The changelog for v0.3.0 mentions "CUDA support for RTX 50-series GPUs", but generation still fails with:
**torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device**

The server log shows the bundled PyTorch only supports up to sm_90:
**The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.**

RTX 50-series (Blackwell) requires PyTorch compiled with CUDA 12.8+ and sm_120 support (torch 2.7.0+cu128 or newer). The bundled torch in the CUDA backend needs to be updated to include sm_120 kernels.
Workaround I found for other projects: manually installing torch-2.7.0+cu128-cp310-cp310-win_amd64.whl from the official PyTorch wheel index resolves the issue, but this is not possible with VoiceBox's bundled environment.
Please update the bundled PyTorch in the CUDA backend to a version compiled with sm_120 support.

**Comment by pritam4249** [comment]
Yes, similar error while running in 5060ti, kindly fix this issue in next update. We need to use CPU currently.

**Comment by duquevazzaro** [comment]
I've compiled a version that includes CUDA support for the RTX 50 Series. I have an RTX 5080, and it works perfectly. If anyone's interested, I'll upload the release to my GitHub so you can try it out and give me some feedback.

**Comment by omnsnr** [comment]
> I've compiled a version that includes CUDA support for the RTX 50 Series. I have an RTX 5080, and it works perfectly. If anyone's interested, I'll upload the release to my GitHub so you can try it out and give me some feedback.

That would be great

**Comment by duquevazzaro** [comment]
> > I've compiled a version that includes CUDA support for the RTX 50 Series. I have an RTX 5080, and it works perfectly. If anyone's interested, I'll upload the release to my GitHub so you can try it out and give me some feedback.
> 
> That would be great

In addition to improved compatibility with all RTX 50 Series cards, I’ve implemented 10 additional improvements, including performance enhancements, multilingual app translation, faster load times, and an integrated CUDA library, among others... It’s worth the wait. I’ll have it ready and compiled for Windows in a few hours. Stay tuned

**Comment by duquevazzaro** [comment]
> VoiceBox v0.3.0, Windows 11, NVIDIA GeForce RTX 5080 The changelog for v0.3.0 mentions "CUDA support for RTX 50-series GPUs", but generation still fails with: **torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device**
> 
> The server log shows the bundled PyTorch only supports up to sm_90: **The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90. NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.**
> 
> RTX 50-series (Blackwell) requires PyTorch compiled with CUDA 12.8+ and sm_120 support (torch 2.7.0+cu128 or newer). The bundled torch in the CUDA backend needs to be updated to include sm_120 kernels. Workaround I found for other projects: manually installing torch-2.7.0+cu128-cp310-cp310-win_amd64.whl from the official PyTorch wheel index resolves the issue, but this is not possible with VoiceBox's bundled environment. Please update the bundled PyTorch in the CUDA backend to a version compiled with sm_120 support.

Ready guys https://github.com/duquevazzaro/clonvoice-releases/tree/main
Buy me a coffee :)
