### ISSUE TITLE
GPU NOT AVAILABLE

### ISSUE THREAD

**Issue by lazyboy9399** [jamiepine/voicebox#66]
I can't customize the GPU; the app only uses the CPU for reading.
<img width="1043" height="497" alt="Image" src="https://github.com/user-attachments/assets/a77ea9b7-37e0-4c9a-8ef0-8739f42e02d9" />

**Comment by lazyboy9399** [comment]
What should I do? 😭

**Comment by aptonline** [comment]
It may help to provide the dev some additional information about your setup, hardware, OS etc.

**Comment by backendiain** [comment]
For what it's worth, this could be due to the versions of PyTorch used. It's not the dev's fault, PyTorch versions can have pretty patchy support for detecting CUDA (or ROCM/HIP) functionality on GPUs.

I'd encountered this before on a few other AI libs like Automatic1111 and ComfyUI. It's not uncommon.

Hopefully this works for you!

### Fix
In the root directory of the project run:
`pip uninstall -y torch torchvision torchaudio `

Then run one of the later install scripts depending on your Python package/environment manager (pip, conda etc.).

For example Windows and an Nvidia GPU:
```
# CUDA 12.6
pip install torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1 --index-url https://download.pytorch.org/whl/cu126
```

Torch v2.9.1 with ROCm v6.4 seems to work fine for me on Linux with my AMD GPU.

https://pytorch.org/get-started/previous-versions/

You can update the requirements.txt files but you'll probably only sort it once.

### Confirming Fix
To confirm whether updating the packages has done the trick create a small cuda_test.py script in the project root:
```
import torch;
print(torch.__version__);
print(torch.cuda.is_available());
```

Then just run it with:
`python cuda_test.py`

Which should output something like:
```
2.9.1+rocm6.4
True
```

You could even tweak startup_event() in backend/main.py if you wanted to really check stuff in-situ:
https://github.com/jamiepine/voicebox/blob/main/backend/main.py#L1654

### Booting
The make command seems to fail to detect things still but you can boot the backend separately with:
`python -m uvicorn backend.main:app --host 127.0.0.1 --port 17493 --reload`

That'll probably be available in your browser:
http://localhost:5173/

If you still want to run things with the Makefile you can actually just boot the backend separately then in the project root do:
`make dev`

The boot script realises the backend is already running and just carries on as normal.

**Comment by backendiain** [comment]
@lazyboy9399 @arizonaicetee ^^

**Comment by aptonline** [comment]
> [@aptonline](https://github.com/aptonline) there's no reason to provide the dev with any additional info because this is not an isolated case, gpu support isn't available for anyone using it on windows

The fact that the OP didn't mentioned Windows is what I was referring to.  Something is better than nothing.

**Comment by jonathanduke** [comment]
I'm on Windows. When I ran the pip install command...
```
voicebox\backend> pip install -r requirements.txt
```
... it downloaded the CPU-only version of PyTorch.

I tested with this Python script:
```python
import torch;
print(torch.__version__);
print(torch.cuda.is_available());
x = torch.rand(5, 3);
print(x);
```

The output was:
```
2.10.0+cpu
False
tensor([[0.7072, 0.8646, 0.0691],
        [0.3879, 0.3203, 0.6988],
        [0.6005, 0.6138, 0.3226],
        [0.8687, 0.5691, 0.0600],
        [0.4282, 0.7621, 0.5277]])
```

After downgrading to 2.9.1 with CUDA 12.6 per the comment by @backendiain, It worked:
```
2.9.1+cu126
True
tensor([[0.8214, 0.7575, 0.4679],
        [0.1698, 0.8639, 0.2331],
        [0.3375, 0.9133, 0.6852],
        [0.4393, 0.2162, 0.3307],
        [0.1758, 0.1239, 0.7720]])
```

So, I uninstalled all versions of torch, and I also purged the pip cache to make sure it doesn't use the old CPU-only version:
```
pip uninstall -y torch torchaudio torchvision
pip cache purge
```

... and then I added these two lines at the top of requirements.txt:

```
--index-url https://download.pytorch.org/whl/cu126
--extra-index-url https://pypi.org/simple
```

I reran pip install on the backend as above in step 1, and it installed the CUDA version of PyTorch this time (you can tell the difference, because the CPU-only version is about 100 MB, but the CUDA version is 2.6 GB). Now my output shows:
```
2.10.0+cu126
True
tensor([[0.1747, 0.9741, 0.0810],
        [0.3798, 0.3631, 0.1502],
        [0.9607, 0.0790, 0.9533],
        [0.6721, 0.2993, 0.2743],
        [0.0161, 0.1372, 0.2742]])
```

When I hit the /health endpoint on the API now, I see my GPU model and VRAM instead of seeing "null" entries as I was seeing before.

Hope that helps somebody.

**Comment by jamiepine** [comment]
This should be resolved in **Voicebox v0.2.x**! 🎉

GPU detection and CUDA support have been completely reworked:

- **CUDA backend swap** — the app now ships with a CPU backend by default, and you can download and install the CUDA-accelerated backend directly from **Settings → GPU Acceleration**. No reinstall or manual setup required.
- **AMD ROCm** support on Linux
- **Intel Arc (XPU)** and **DirectML** support on Windows

If you're on Windows with an NVIDIA GPU: update to v0.2.x, go to Settings → GPU Acceleration, and download the CUDA backend. It'll swap in automatically and your GPU should be detected on the next generation.

**To get the update:**
- Download the latest release from [voicebox.sh](https://voicebox.sh) or update from within the app

Closing as resolved — if you still have GPU detection issues on v0.2.x after installing the CUDA backend, please open a new issue with your GPU model and OS details!
