### ISSUE TITLE
GPU: Not Available

### ISSUE THREAD

**Issue by StephanBaum** [jamiepine/voicebox#84]
My gpu is not recognized.
its a 4090 with latest studio drivers. should be good for this.
unfortunately there is nothing more to tell.  =)

**Comment by KotPrezesOfficial** [comment]
Same here. I downloaded win10 ver and got 4060 and only CPU is used.

**Comment by thespenceryan** [comment]
Same, 4090 here.

**Comment by ArtefactDesigntn** [comment]
same here 3060

**Comment by Akiwuff** [comment]
Same problem on Windows 10, got a 3090. Other applications that use PyTorch work and use the GPU.

**Comment by mrj0b** [comment]
same problem windows 11 25h2 rtx 3080

**Comment by TomerGamerTV** [comment]
Same

**Comment by vo001** [comment]
Same RTX5080 windows 10

**Comment by TheBeaconCrafter** [comment]
Same here, RTX 2080 on Windows 11

**Comment by Kirasabi** [comment]
For thoose who has that issue, (for now you need build your own version, gpu support **seems like** doesn't work on prebuild.exe variants.
So, you must have all dependecies such as: [Bun](https://bun.sh/), [Rust](https://rustup.rs/), [Python 3.11+](https://python.org/).

Then, install app through git clone as described here (Manual setup (all platforms): https://github.com/jamiepine/voicebox?tab=readme-ov-file#quick-start


Then, you need to install torch/torchvision/torchaudio (though im too braindead and didn't manage to create venv) so i've just installed those into my system **Be careful with that since, if you have several AI on system working without venv, it's may overwrite your torch, pythorch torchaudio versions.**
So, to install that you need first run in cmd 
```
pip uninstall -y torch torchvision torchaudio
``` 
and after that 
```
pip install torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1 --index-url https://download.pytorch.org/whl/cu126
```
i just used thoose [described here ](https://github.com/jamiepine/voicebox/issues/66#issuecomment-3893267190)

and then for quality of life, create bat file inside folder and put that lines inside 
(i had issues with downloading/fetching/downloading and after several hours figured out that i need run 2 cmd's at same time)
```
@echo off
start cmd /k "python -m uvicorn backend.main:app --host 127.0.0.1 --port 17493 --reload"
bun run dev
```

**Comment by Akiwuff** [comment]
Thank you, Kirasabi, for this workaround. Unfortunately, manually installing this and all the dependencies is the complete opposite of what I am looking for. :) What makes Voicebox extremely attractive to me is the "fire and forget" installation procedure, which would allow it to hand it to someone who is not literate in setting up a python environment and so on. Therefore, I am just going to wait till this bug is fixed in a way that makes voicebox work "out of the box", as I believe it is intended to do.

**Comment by BonifacioCalindoro** [comment]
> For thoose who has that issue, (for now you need build your own version, gpu support **seems like** doesn't work on prebuild.exe variants. So, you must have all dependecies such as: [Bun](https://bun.sh/), [Rust](https://rustup.rs/), [Python 3.11+](https://python.org/).
> 
> Then, install app through git clone as described here (Manual setup (all platforms): https://github.com/jamiepine/voicebox?tab=readme-ov-file#quick-start
> 
> Then, you need to install torch/torchvision/torchaudio (though im too braindead and didn't manage to create venv) so i've just installed those into my system **Be careful with that since, if you have several AI on system working without venv, it's may overwrite your torch, pythorch torchaudio versions.** So, to install that you need first run in cmd
> 
> ```
> pip uninstall -y torch torchvision torchaudio
> ```
> 
> and after that
> 
> ```
> pip install torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1 --index-url https://download.pytorch.org/whl/cu126
> ```
> 
> i just used thoose [described here ](https://github.com/jamiepine/voicebox/issues/66#issuecomment-3893267190)
> 
> and then for quality of life, create bat file inside folder and put that lines inside (i had issues with downloading/fetching/downloading and after several hours figured out that i need run 2 cmd's at same time)
> 
> ```
> @echo off
> start cmd /k "python -m uvicorn backend.main:app --host 127.0.0.1 --port 17493 --reload"
> bun run dev
> ```

Nice workaround! In my case, i was receiving some warnings in the backend logs because the cuda version was not 100% compatible with my RTX 5090 laptop gpu. The solution was to change the --index-url to https://download.pytorch.org/whl/cu128 (12.8 version instead of 12.6). 

In my case, instead of uninstalling and reinstalling torch, what i did was adding these two lines to the top of the backend/requirements.txt file:

```
--index-url https://download.pytorch.org/whl/cu128
--extra-index-url https://pypi.org/simple
```

And then install the requirements on a venv rather than rawdogging them into the user environment. So basically,  cd backend -> python -m venv .venv -> .venv/scripts/activate -> pip install -r requirements.txt

And then on the .bat file, change the 2nd line to 
```
start cmd /k ".\backend\.venv\scripts\python -m uvicorn backend.main:app --host 127.0.0.1 --port 17493 --reload"
```

**Comment by gtajulianandreas-spec** [comment]
same issue here, the app only uses my CPU

**Comment by CHKE9** [comment]
anyway to fix this on .exe app version?

**Comment by sameul674** [comment]
anyone knows when this will get fixed? it takes hella long time to generate even a small voice clip

**Comment by dschiller** [comment]
Same here with latest Pinokio and latest Voicebox.

**Comment by sumire608** [comment]
https://github.com/sumire608/voicebox/releases/tag/v0.1.13
I build with CUDA ver 0.1.13, you can try it.

**Comment by rawzone** [comment]
> https://github.com/sumire608/voicebox/releases/tag/v0.1.13 I build with CUDA ver 0.1.13, you can try it.

@sumire608 I tried your bild and it sadly stil didn't use the GPU for me.

**Comment by sumire608** [comment]
You may need to use taskmgr and killed "voicebox-server.exe" processes manually, because they won't exit automatically. Then try again.

**Comment by rawzone** [comment]
I've tried both terminating the `voicebox-server.exe` via the taskmanager and done a full system reboot.
(Voicebox is not set to auto-run on login and checked that the server didn't run before manual starting Voicebox)

Bud sadle still no GPU support on my end - I'll try to do a bit of debugging once of these days and update if I get it running.

**Comment by Akiwuff** [comment]
> Bud sadle still no GPU support on my end - I'll try to do a bit of debugging once of these days and update if I get it running.

Check your driver version. Cuda 13 is not supported by older versions, I ran into some wired problems with Comfy because of that as well.

**Comment by sumire608** [comment]
I may got the release files wrong. So I build it again today. Make sure the file is 1.88GB.
https://github.com/sumire608/voicebox/releases

**Comment by Clatasha** [comment]
> https://github.com/sumire608/voicebox/releases/tag/v0.1.13 I build with CUDA ver 0.1.13, you can try it.

im gona try

**Comment by Insanitier** [comment]
> I may got the release files wrong. So I build it again today. Make sure the file is 1.88GB. https://github.com/sumire608/voicebox/releases

it works!

**Comment by 42531ljm** [comment]
same

**Comment by jamiepine** [comment]
This should be resolved in **Voicebox v0.2.x**! 🎉

GPU detection and CUDA support have been completely reworked:

- **CUDA backend swap** — the app now ships with a CPU backend by default, and you can download and install the CUDA-accelerated backend directly from **Settings → GPU Acceleration**. No reinstall or manual setup required.
- **AMD ROCm** support on Linux
- **Intel Arc (XPU)** and **DirectML** support on Windows

If you're on Windows with an NVIDIA GPU: update to v0.2.x, go to Settings → GPU Acceleration, and download the CUDA backend. It'll swap in automatically and your GPU should be detected on the next generation.

**To get the update:**
- Download the latest release from [voicebox.sh](https://voicebox.sh) or update from within the app

Closing as resolved — if you still have GPU detection issues on v0.2.x after installing the CUDA backend, please open a new issue with your GPU model and OS details!

**Comment by rawzone** [comment]
When clicking to download the CUDA backend I end up with the following error:

<img width="552" height="313" alt="Image" src="https://github.com/user-attachments/assets/6e2a23e7-a976-4352-bc7b-112521ce1d3e" />

This is on a fresh re-installed version of Voicebox (v0.2.3).

**Comment by Typhooni** [comment]
I still have this issue with an AMD 6900XT...
